name: OWASP ZAP Baseline Scan

on:
  workflow_run:
    workflows: ["VM Deploy NodeBB"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read # for actions/checkout to fetch code
  issues: write # for zaproxy/action-baseline@v0.14.0 to create issue for alerts

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: "production"
      DEEPSEEK_API_ACCESS_TOKEN: ${{ secrets.DEEPSEEK_API_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
