name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - main
      - newMain
  pull_request:
    branches:
      - main
      - newMain
  workflow_call: # Usually called from deploy

defaults:
  run:
    shell: bash

permissions:
  contents: read # for actions/checkout to fetch code
  issues: write # for zaproxy/action-baseline@v0.14.0 to create issue for alerts

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: "production"
      DEEPSEEK_API_ACCESS_TOKEN: ${{ secrets.DEEPSEEK_API_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ secrets.ZAP_TARGET }}